# Pandas 2 : 집계, 결합

## 환경준비 + 데이터 로드

* 라이브러리 불러오기

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

* 데이터 로딩

In [ ]:
# 데이터1 : 보스톤 타운별 집값
boston = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/boston2.csv")
boston.head()

In [ ]:
# 데이터2 : 타이타닉 승객 생존여부
titanic = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic.0.csv")
titanic.head()

## Dataframe 다루기

### 5.1 결합 1 : 조인 join(merge)

- 결합은 나눠어진 데이터셋으로 부터 하나로 모으는 작업입니다.

* 판다스에서 join은 굉장히 간단합니다.
* 자동으로 key를 잡아줍니다
* default로 inner join을 합니다.

In [ ]:
sales = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/sales.csv")
products = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/products.csv")

In [ ]:
sales.head()

In [ ]:
products.head()

In [ ]:
pd.merge(sales, products).head() # 공통된 칼럼이 있으면 그 칼럼을 key로 사용

how 파라미터에 값을 지정하여 outer join을 수행합니다.

how='inner'

==> left, right, outer

In [ ]:
pd.merge(sales, products, how='left').head()

### 실습 6 : Join(Merge) + groupby

* Q1. sales와 products를 ProductID 기준으로 merge하여 새로운 데이터프레임으로 저장합니다.

* Q2. Category별 총 매출액(amt)

* Q3. Category별 총 판매량 (qty)

* Q4. 전체에서 가장 매출이 높은 상품명 10개 조회

### 5.3 결합 2 : 붙이기  concat( )

* 방금 전 실습에서 2,3번의 결과를 각각 dataframe으로 저장하시오.

In [ ]:
data2 = data.groupby('Category', as_index=False)['Amt'].sum()
data3 = data.groupby('Category', as_index=False)['Qty'].sum()

* 위 아래로 붙이기

In [ ]:
pd.concat([data2, data3])

* 옆으로 붙이기

In [ ]:
pd.concat([data2, data3], axis=1)

### 실습 7. concat( )

* Q1. 2016년 1월 데이터를 가진 데이터프레임과 2017년 1월 데이터를 가진 데이터프레임을 만드시오.

* Q2. Q1에서 만든 데이터프레임을 위, 아래로 붙이시오.

### 5.4 추가 : Rolling & Shift
 - rolling은 주로 시계열 데이터에 대해서 이동평균값을 구하거나, 행을 shift(이동) 시킬 때 주로 사용합니다.
 - 시계열 데이터 : 행과 행에 시간순서가 있는 데이터(전제 : 시간순으로 정렬 되어 있는 상태)

In [ ]:
import pandas as pd

In [ ]:
stock = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/SK.csv') 
stock.head()

* stock 데이터프레임에서 Date, Close, Volume 만을 남깁니다.

In [ ]:
# stock.drop으로 칼럼을 삭제할수도 있고, 아래와 같이 특정 칼럼으로 구성된 데이터프레임을 만들수도 있습니다.
stock = stock[['Date', 'Close', 'Volume']]
#stock = stock.loc[:, ['Date', 'Close', 'Volume']]

stock.head()

기준일 포함하여 과거 3일의 평균을 데이터 프레임에 붙여봅시다.

In [ ]:
stock['Close_MA_3'] = stock['Close'].rolling(3).mean()
stock.head(10)

In [ ]:
stock['Close_MA_3_lag1'] = stock['Close_MA_3'].shift() # shift()안에 숫자를 변경해 보며 기능을 알아보자. default = 1
stock.head(10)

In [ ]:
# 이동평균(rolling)과 하루 뒤로 미루는(shift) 작업을 한꺼번에 하려면?
stock['Close_MA_3_lag1_2'] = stock['Close'].rolling(3).mean().shift()
stock.head(10)

min_periods를 기억하자

In [ ]:
stock['Close_MA_3(2)'] = stock['Close'].rolling(3, min_periods=1).mean()
stock.head()

### 실습 8 : Rolling & Shift

* 아래 셀을 실행한 후 진행하시오

In [ ]:
stock = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/sknetworks.csv', sep=',', skipinitialspace=True) 
stock = stock[['Date', 'Close', 'Volume']]
stock.head()

* Q1. stock 데이터프레임에 전날 주가 컬럼과 전전날 주가 컬럼을 추가하세요.

* Q2. 전전날 대비 전날 주가 증감 컬럼을 추가하세요.

* Q3. Q2에서 만든 컬럼의 각 데이터가 양수이면 1, 음수이면 0인 컬럼을 추가하세요.

* Q4. 3일 이동 최대 주가를 추가하세요.

* Q5. 기준일을 포함하지 않은, 과거 3일의 최대 주가를 추가하세요.

* Q6. 기준일을 포함하지 않은, 과거 7일 평균 거래량을 추가하세요.

* Q7. 기준일을 포함하지 않은 과거 7일 평균 거래량을 추가하되, 최소 1일 데이터만 있어도 평균값이 나오게 만드시오.